export const ATHLETIC_TAG_ALL = [
  { label: "合気道", path: "aikido" },
  { label: "アイスホッケー", path: "icehockey" },
  { label: "アウトドア", path: "outdoor-ath" },
  { label: "アメリカンフットボール", path: "americanfootboll" },
  { label: "アルティメット", path: "ultimate" },
  { label: "アーチェリー", path: "archery" },
  { label: "居合道", path: "iaidou" },
  { label: "応援", path: "cheering-ath" },
  { label: "オリエンテーリング", path: "orienteering" },
  { label: "オールラウンド", path: "allround" },
  { label: "カヌー", path: "canoe" },
  { label: "空手", path: "karate" },
  { label: "カーリング", path: "kahling" },
  { label: "クライミング", path: "climbing" },
  { label: "剣道", path: "kendo" },
  { label: "航空", path: "aviation" },
  { label: "ゴルフ", path: "golf" },
  { label: "サッカー", path: "soccer" },
  { label: "山岳", path: "mountain" },
  { label: "少林寺拳法", path: "shorinji" },
  { label: "自転車", path: "bicycle" },
  { label: "自動車", path: "automobile" },
  { label: "柔道", path: "judo" },
  { label: "水泳", path: "swimming" },
  { label: "スカッシュ", path: "squash" },
  { label: "スキー", path: "ski" },
  { label: "スポーツチャンバラ", path: "chambara" },
  { label: "相撲", path: "sumo" },
  { label: "セパタクロー", path: "sepaktakraw" },
  { label: "ソフトボール", path: "softball" },
  { label: "体操", path: "gymnastics" },
  { label: "躰道部", path: "taido" },
  { label: "卓球", path: "tabletennis" },
  { label: "ダイビング", path: "diving" },
  { label: "ダンス", path: "dance" },
  { label: "チアリーダー", path: "cheerleading" },
  { label: "テコンドー", path: "taekwondo" },
  { label: "テニス", path: "tennis" },
  { label: "トライアスロン", path: "triathlon" },
  { label: "バイク", path: "bike" },
  { label: "馬術", path: "equestrian" },
  { label: "バスケットボール", path: "basketball" },
  { label: "バドミントン", path: "badminton" },
  { label: "バレーボール", path: "volleyball" },
  { label: "パルクール", path: "parkour" },
  { label: "フィギュアスケート", path: "figureskating" },
  { label: "フェンシング", path: "fencing" },
  { label: "フットサル", path: "footsal" },
  { label: "ホッケー", path: "hockey" },
  { label: "ボクシング", path: "boxing" },
  { label: "ボブスレー・リュージュ・スケルトン", path: "bobsled" },
  { label: "ボート", path: "boat" },
  { label: "モルック", path: "molkky" },
  { label: "野球", path: "baseball" },
  { label: "ヨット", path: "yacht" },
  { label: "ライフル射撃", path: "lifle" },
  { label: "ラクロス", path: "lacrosse" },
  { label: "陸上競技", path: "track" },
  { label: "ワンダーフォーゲル", path: "wandervogel" },
]

export const ATHLETIC_TAG_POPULAR = [
  { label: "テニス", path: "tennis" },
  { label: "野球", path: "baseball" },
  { label: "スキー", path: "ski" },
  { label: "サッカー", path: "soccer" },
  { label: "バレーボール", path: "volleyball" },
  { label: "ダンス", path: "dance" },
  { label: "陸上競技", path: "track" },
  { label: "バスケットボール", path: "basketball" },
  { label: "合気道", path: "aikido" },
]

export const CULTURAL_TAG_ALL = [
  { label: "アウトドア", path: "outdoor-cul" },
  { label: "映画", path: "cinema" },
  { label: "英語", path: "english" },
  { label: "演劇", path: "drama" },
  { label: "応援", path: "cheering-cul" },
  { label: "音楽", path: "music" },
  { label: "教育", path: "education" },
  { label: "クリエイティブ", path: "creative" },
  { label: "研究", path: "study" },
  { label: "ゲーム", path: "game" },
  { label: "国際", path: "international" },
  { label: "食", path: "food" },
  { label: "地学", path: "geoscience" },
  { label: "農業", path: "agriculture" },
  { label: "文化・芸術", path: "culture-art" },
  { label: "ボランティア", path: "volunteer" },
  { label: "よさこい", path: "yosakoi" },
  { label: "旅行", path: "trip" },
]

export const CULTURAL_TAG_POPULAR = [
  { label: "音楽", path: "music" },
  { label: "研究", path: "study" },
  { label: "クリエイティブ", path: "creative" },
  { label: "ボランティア", path: "volunteer" },
  { label: "文化・芸術", path: "culture-art" },
  { label: "国際", path: "international" },
  { label: "アウトドア", path: "outdoor-cul" },
]
