export const ATHLETIC_TAG_ALL = [
  { label: "合気道", path: "/athletic/aikido" },
  { label: "アイスホッケー", path: "/athletic/icehockey" },
  { label: "アウトドア", path: "/athletic/outdoor-ath" },
  { label: "アメリカンフットボール", path: "/athletic/americanfootball" },
  { label: "アルティメット", path: "/athletic/ultimate" },
  { label: "アーチェリー", path: "/athletic/archery" },
  { label: "居合道", path: "/athletic/iaidou" },
  { label: "応援", path: "/athletic/cheering-ath" },
  { label: "オリエンテーリング", path: "/athletic/orienteering" },
  { label: "オールラウンド", path: "/athletic/allround" },
  { label: "カヌー", path: "/athletic/canoe" },
  { label: "空手", path: "/athletic/karate" },
  { label: "カーリング", path: "/athletic/kahling" },
  { label: "クライミング", path: "/athletic/climbing" },
  { label: "剣道", path: "/athletic/kendo" },
  { label: "航空", path: "/athletic/aviation" },
  { label: "ゴルフ", path: "/athletic/golf" },
  { label: "サッカー", path: "/athletic/soccer" },
  { label: "山岳", path: "/athletic/mountain" },
  { label: "少林寺拳法", path: "/athletic/shorinji" },
  { label: "自転車", path: "/athletic/bicycle" },
  { label: "自動車", path: "/athletic/automobile" },
  { label: "柔道", path: "/athletic/judo" },
  { label: "水泳", path: "/athletic/swimming" },
  { label: "スカッシュ", path: "/athletic/squash" },
  { label: "スキー", path: "/athletic/ski" },
  { label: "スポーツチャンバラ", path: "/athletic/chambara" },
  { label: "相撲", path: "/athletic/sumo" },
  { label: "セパタクロー", path: "/athletic/sepatakraw" },
  { label: "ソフトボール", path: "/athletic/softball" },
  { label: "体操", path: "/athletic/gymnastics" },
  { label: "躰道部", path: "/athletic/taido" },
  { label: "卓球", path: "/athletic/tabletennis" },
  { label: "ダイビング", path: "/athletic/diving" },
  { label: "ダンス", path: "/athletic/dance" },
  { label: "チアリーダー", path: "/athletic/cheerleading" },
  { label: "テコンドー", path: "/athletic/taekwondo" },
  { label: "テニス", path: "/athletic/tennis" },
  { label: "トライアスロン", path: "/athletic/triathlon" },
  { label: "バイク", path: "/athletic/bike" },
  { label: "馬術", path: "/athletic/equestrian" },
  { label: "バスケットボール", path: "/athletic/basketball" },
  { label: "バドミントン", path: "/athletic/badminton" },
  { label: "バレーボール", path: "/athletic/volleyball" },
  { label: "パルクール", path: "/athletic/parkour" },
  { label: "フィギュアスケート", path: "/athletic/figureskating" },
  { label: "フェンシング", path: "/athletic/fencing" },
  { label: "フットサル", path: "/athletic/futsal" },
  { label: "ホッケー", path: "/athletic/hockey" },
  { label: "ボクシング", path: "/athletic/boxing" },
  { label: "ボブスレー・リュージュ・スケルトン", path: "/athletic/bobsled" },
  { label: "ボート", path: "/athletic/boat" },
  { label: "モルック", path: "/athletic/molkky" },
  { label: "野球", path: "/athletic/baseball" },
  { label: "ヨット", path: "/athletic/yacht" },
  { label: "ライフル射撃", path: "/athletic/lifle" },
  { label: "ラクロス", path: "/athletic/lacrosse" },
  { label: "陸上競技", path: "/athletic/track" },
  { label: "ワンダーフォーゲル", path: "/athletic/wandervogel" },
]

export const ATHLETIC_TAG_POPULAR = [
  { label: "テニス", path: "/athletic/tennis" },
  { label: "野球", path: "/athletic/baseball" },
  { label: "スキー", path: "/athletic/ski" },
  { label: "サッカー", path: "/athletic/soccer" },
  { label: "バレーボール", path: "/athletic/volleyball" },
  { label: "ダンス", path: "/athletic/dance" },
  { label: "陸上競技", path: "/athletic/track" },
  { label: "バスケットボール", path: "/athletic/basketball" },
  { label: "合気道", path: "/athletic/aikido" },
]
export const ATHLETIC_TAG_FOR_ATHLETIC = [
  { label: "アメリカンフットボール", path: "/athletic/americanfootball" },
  { label: "パルクール", path: "/athletic/parkour" },
  { label: "オリエンテーリング", path: "/athletic/orienteering" },
  { label: "応援", path: "/athletic/cheering-ath" },
  { label: "ダイビング", path: "/athletic/diving" },
  { label: "ラクロス", path: "/athletic/lacrosse" },
  { label: "ヨット", path: "/athletic/yacht" },
  { label: "自転車", path: "/athletic/bicycle" },
  { label: "居合道", path: "/athletic/iaidou" },
  { label: "ワンダーフォーゲル", path: "/athletic/wandervogel" },
  { label: "アイスホッケー", path: "/athletic/icehockey" },
]

export const ATHLETIC_TAG_FOR_CULTURAL = [
  { label: "アーチェリー", path: "/athletic/archery" },
  { label: "ゴルフ", path: "/athletic/golf" },
  { label: "モルック", path: "/athletic/molkky" },
  { label: "馬術", path: "/athletic/equestrian" },
  { label: "バドミントン", path: "/athletic/badminton" },
  { label: "スカッシュ", path: "/athletic/squash" },
  { label: "山岳", path: "/athletic/mountain" },
  { label: "フィギュアスケート", path: "/athletic/figureskating" },
]

export const CULTURAL_TAG_ALL = [
  { label: "アウトドア", path: "/cultural/outdoor-cul" },
  { label: "映画", path: "/cultural/cinema" },
  { label: "英語", path: "/cultural/english" },
  { label: "演劇", path: "/cultural/drama" },
  { label: "応援", path: "/cultural/cheering-cul" },
  { label: "音楽", path: "/cultural/music" },
  { label: "教育", path: "/cultural/education" },
  { label: "クリエイティブ", path: "/cultural/creative" },
  { label: "研究", path: "/cultural/study" },
  { label: "ゲーム", path: "/cultural/game" },
  { label: "国際", path: "/cultural/international" },
  { label: "食", path: "/cultural/food" },
  { label: "地学", path: "/cultural/geoscience" },
  { label: "農業", path: "/cultural/agriculture" },
  { label: "文化・芸術", path: "/cultural/culture-art" },
  { label: "ボランティア", path: "/cultural/volunteer" },
  { label: "よさこい", path: "/cultural/yosakoi" },
  { label: "旅行", path: "/cultural/trip" },
]

export const CULTURAL_TAG_POPULAR = [
  { label: "音楽", path: "/cultural/music" },
  { label: "研究", path: "/cultural/study" },
  { label: "クリエイティブ", path: "/cultural/creative" },
  { label: "ボランティア", path: "/cultural/volunteer" },
  { label: "文化・芸術", path: "/cultural/humanities" },
  { label: "国際", path: "/cultural/international" },
  { label: "アウトドア", path: "/cultural/outdoor-cul" },
]
